### ISSUE TITLE
Cannot compile cabal after upgrading to Plutus V2

### ISSUE THREAD

**Issue by matteocoppola** [mlabs-haskell/plutus-simple-model#53]
I get the following error when trying to run **cabal build**:
![immagine](https://user-images.githubusercontent.com/46167820/194530285-a745474c-04f3-441d-80ae-2b2192b6101a.png)

My cabal.project tries to include Plutus Simple Model as follows:
![immagine](https://user-images.githubusercontent.com/46167820/194530500-5c0aaa08-946a-4b53-9181-5795958938ab.png)

I'm not sure how I can solve this, it's the latest commit of master branch.

**Comment by AriFordsham** [comment]
@matteocoppola Is this still an issue?
