### ISSUE TITLE
`spend` failing with `fromJust` error

### ISSUE THREAD

**Issue by KristianBalaj** [mlabs-haskell/plutus-simple-model#68]
The `spend` function should fail with more useful error message.
The change could be as proposed here https://github.com/mlabs-haskell/plutus-simple-model/pull/67#discussion_r1047379217

**Comment by AriFordsham** [comment]
The `spend'` function is total, and intended for error recovery.

The purpose of the `spend` function is when you intend to guarantee that there are sufficient funds available, and hence it will never fail.

**Comment by KristianBalaj** [comment]
Yeah but still when it fails, the `fromJust` here:
https://github.com/mlabs-haskell/plutus-simple-model/blob/8bd477001f9223bfd4a0d3fabd63e8bf957a12d2/src/Plutus/Model/Contract.hs#L276
throws an error that doesn't describe the problem just informs the user that `Nothing` appeared somewhere.

**Comment by AriFordsham** [comment]
`Nothing` only appears when there are insufficient funds to spend.

**Comment by KristianBalaj** [comment]
Yeah, but there's no callstack, no useful error message, so it's hard to debug why a test failed.
