### ISSUE TITLE
Factor Cardano layer into separate package

### ISSUE THREAD

**Issue by AriFordsham** [mlabs-haskell/plutus-simple-model#87]
psm has its own lightweight wrapper layer of Cardano functions, kept in the `Fork.*` hierarchy. These are considered internal modules and not exposed.

The problem is that hedgehog-plutus-simple (and potentially other packages) need many of these functions. The current solution, maintaining a branch of psm where these are exposed, is not satisfactory in the long term.

The proposed solution is to move these modules into a separate package, that both psm and hps can depend on.

- [x] Create a new repository, maybe `cardano-simple`, based on mlabs-tooling.
- [x] Move the `Fork` hierarchy to this repo. Probably remove the `Fork` prefix and add a suffix such as `Simple` to to each non-novel module 
- [x] Switch psm to new dependency
- [x] Switch hps to the new dependency.

When this is done, it may be interesting to see what functionality that hps has duplicated from psm can be removed by exposing more functions from the new Cardano layer, or possibly even moving useful functionality from psm proper to the new layer.

The overarching goal is to move towards a tidier design on all three modules.

**Comment by Geometer1729** [comment]
Completed in:
https://github.com/mlabs-haskell/plutus-simple-model/pull/88
and
https://github.com/mlabs-haskell/hedgehog-plutus-simple/pull/25
